FROM docker.wso2.com/wso2mi:4.0.0.0
LABEL maintainer="WSO2 Docker Maintainers <dev@wso2.org>"

# copy CAR files to the MI server home
COPY capps ${WSO2_SERVER_HOME}/repository/deployment/server/carbonapps/
